name = "RGRDMT"
uuid = "e72673de-515e-43cd-97ad-2e67cb62347d"
authors = ["Yusheng Zhao <yushengzhao2020@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
MPSKit = "bb1c41ca-d63c-52ed-829e-0820dda26502"
MPSKitModels = "ca635005-6f8c-4cd1-b51d-8491250ef2ab"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
